AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for To Do Application...
  App is running on Python Flask Framework..
Parameters:
  EC2ImageId:
    Description: Select image id
    Type: AWS::EC2::Image::Id
Resources:
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for To Do Web API #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref EC2ImageId
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: 
        Fn::Base64:
          !Sub 
            - |
              #! /bin/bash
              yum update -y
              yum install python3 -y
              pip3 install flask
              pip3 install flask_mysql
              echo "${MyDBURI}" > /home/ec2-user/dbserver.endpoint
              FOLDER="https://github.com/ajayram91/PythonApplications/blob/master/To-Do%20Web%20API%20(Python%20Flask)%20deployed%20on%20AWS%20EC2%20and%20RDS%20using%20Cloudformation/"
              curl -s --create-dirs -o "/home/ec2-user/app.py" -L "$FOLDER"/to-do-api.py
              python3 /home/ec2-user/app.py
            - MyDBURI: !GetAtt MyDatabaseServer.Endpoint.Address

  MyDBSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      DBSecurityGroupIngress: #required
        - EC2SecurityGroupId: !GetAtt WebServerSecurityGroup.GroupId
      GroupDescription: Webserver Access #required

  MyDatabaseServer:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro #required
      DBName: todo_db
      DBSecurityGroups:
        - !Ref MyDBSecurityGroup
      Engine: MySQL
      EngineVersion: 8.0.19
      MasterUserPassword: password
      MasterUsername: admin
      MultiAZ: false
      Port: 3306

Outputs:
  WebsiteURL:
    Description: To Do Web API URL
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
        

    

 






